### ISSUE TITLE
ListFiletypes is undefined.

### ISSUE THREAD

**Issue by ernestzhang-11** [jobvandenhurk/T1T2T2starmappingtool#1]
ListFiletypes is undefined!
Could you help me to solve it?
![image](https://user-images.githubusercontent.com/33014193/58321451-c2ab4b00-7e50-11e9-8b41-1beecf032c05.png)

**Comment by zhangluwei1997** [comment]
@jobvandenhurk

**Comment by ernestzhang-11** [comment]
Hi ! @jobvandenhurk 
vecFreq is undefiend !
![image](https://user-images.githubusercontent.com/33014193/58410751-62f9ad80-80a5-11e9-8017-699c14738667.png)

THX !

**Comment by ernestzhang-11** [comment]
Hi ! @jobvandenhurk 
neardiv is undefined!
![image](https://user-images.githubusercontent.com/33014193/58430776-601aaf00-80dd-11e9-9902-b0b34ad7a422.png)

**Comment by ernestzhang-11** [comment]
Hi ! @jobvandenhurk 
Derivative is undefined!
![image](https://user-images.githubusercontent.com/33014193/58468012-5477c880-816f-11e9-94e2-3c854f7492a2.png)

**Comment by ernestzhang-11** [comment]
@jobvandenhurk  Thank you very much !  I have calculated T1 from your code.  You are great! 
I am a student studying MRI. I want to study how to  calculate T1 from  your code. But the result is only once T1 Mapping picture. Is it normal ? One folder have 8 .IMA, I think the result have eight T1 Mapping picture.  Could you tell me why the result have only one picture ?

Here  is the result .
![image](https://user-images.githubusercontent.com/33014193/58487993-2b6d2d00-819b-11e9-9d87-1750df1b7ba8.png)

But When I press ESC, there is an error: The index is out of range the matrix dimension.

![image](https://user-images.githubusercontent.com/33014193/58488248-9f0f3a00-819b-11e9-9b45-1ea5f782482c.png)

**Comment by jobvandenhurk** [comment]
Dearest,

Thanks for your feedback. I actually quickly wrote this toolbox for some of the stuff that I am doing and wanted to share it with my colleagues via GitHub. I wasn’t expecting to get feedback from Asia, but it helped me to solve some of the problems. Thanks a lot!

To answer your latest question: the T1 is computed from fitting the T1 relaxation curve to the (in your case) 8 datapoints per voxel. That is why only 1 image results from your 8 dicom files.

Best of wishes,

Job

Job van den Hurk, PhD
Assistant professor
Department of Cognitive Neuroscience
Faculty of Psychology and Neuroscience, Maastricht University
Postal address: P.O. Box 616, 6200 MD, Maastricht, the Netherlands
Visiting address: Oxfordlaan 55, 6229 EV Maastricht
T: +31 (0)43 388 5837
http://www.jobvandenhurk.nl

Op 28 mei 2019, om 17:04 heeft zhangluwei1997 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Thank you very much ! I have calculated T1 from your code. You are great!
I am a student studying MRI. I want to study how to calculate T1 from your code. But the result is only once T1 Mapping picture. Is it normal ? One folder have 8 .IMA, I think the result have eight T1 Mapping picture. Could you tell me why the result have only one picture ?

Here is the result .
[image]<https://user-images.githubusercontent.com/33014193/58487993-2b6d2d00-819b-11e9-9d87-1750df1b7ba8.png>

But When I press ESC, there is an error: The index is out of range the matrix dimension.

[image]<https://user-images.githubusercontent.com/33014193/58488248-9f0f3a00-819b-11e9-9b45-1ea5f782482c.png>

**Comment by ernestzhang-11** [comment]
Hi ! @jobvandenhurk 
I have a question:
I just read your code finding your fitting function is different from [paper](https://mri-q.com/uploads/3/4/5/7/34572113/messroghli_et_al-2004-magnetic_resonance_in_medicine.pdf).
![image](https://user-images.githubusercontent.com/33014193/58808997-aa57df00-864d-11e9-9dec-0fc7b59c0024.png)

Could you tell me the reason?
